# Generated by Django 3.2.8 on 2021-11-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='avgRating',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
