# Generated by Django 3.2.8 on 2021-11-07 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_avgrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avgRating',
        ),
    ]
