# Generated by Django 3.2.8 on 2021-11-16 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_alter_product_avgrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='avgRating',
        ),
        migrations.AddField(
            model_name='productrating',
            name='comment',
            field=models.TextField(default='Test', max_length=300),
            preserve_default=False,
        ),
    ]
