# Generated by Django 3.2.8 on 2021-11-26 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='helpful',
            field=models.IntegerField(default=0),
        ),
    ]
